steps:
  # IMPORTANT: Ensure you have a 'checkout' step with fetchDepth: 0
  # at the beginning of your job, if this step is in a new job
  # or if the previous checkout step doesn't have it.
  # Example:
  # - checkout: self
  #   fetchDepth: 0

  - script: |
      pip install pytest pytest-cov

      # Source the shared script to get changed Python files
      source .azure-pipelines/common2/scripts/get-changed-python-files.sh

      if [ "$HAS_CHANGED_PYTHON_FILES" = "false" ]; then
        echo "Skipping Unit Tests with Coverage Check."
      else
        echo "Running Unit Tests with Coverage Check for tests/common2..."
        # The command below will run tests found in 'tests/common2'
        # and collect coverage for source files in 'tests/common2'.
        # It will fail the step if coverage is below 80% due to --cov-fail-under=80.
        pytest tests/common2 --cov=tests/common2 --cov-report=xml --cov-fail-under=80
      fi
    displayName: 'Run Unit Tests with Coverage Check (conditional)'
