steps:
  - script: |
      pip install mypy
      echo "Running mypy"
      # configuration is loaded from pyproject.toml
      mypy tests/common2 || true
    displayName: 'Run mypy static type checker'
