# check if the project has precommit configuration
parameters:
  - name: dependsOn
    type: object
    default: []
    displayName: 'Depends On'

jobs:
  - job: check_for_precommit
    dependsOn: ${{ parameters.dependsOn }}
    displayName: 'Check for pre-commit configuration'
    steps:
    - script: |
        echo "Checking if pre-commit configuration .pre-commit-config.[yaml|yml] exists"
        if [ -f .pre-commit-config.yaml ] || [ -f .pre-commit-config.yml ]; then
          echo "Pre-commit configuration found"
          echo "##vso[task.setvariable variable=exists;isOutput=true]true"
        else
          echo "Pre-commit configuration not found"
          echo "##vso[task.setvariable variable=exists;isOutput=true]false"
        fi
      name: precommit_config
