parameters:
  - name: dependsOn
    type: object
    default: []
    displayName: 'Depends On'

jobs:
  - job: run_black
    dependsOn:
      - check_for_precommit
      - ${{ parameters.dependsOn }}
    condition: eq(dependencies.check_for_precommit.outputs['precommit_config.exists'], 'false')
    displayName: 'Run Black formatter'
    steps:
    - script: |
        pip install black
        echo "Running Black formatter"
        # NOTE the --check flag is used to check if the code is formatted correctly
        # The tool uses configuration from pyproject.toml expected to be available in the
        # root directory of the calling repository
        black --check .
