parameters:
  - name: dependsOn
    type: object
    default: []
    displayName: 'Depends On'

jobs:
  - job: run_precommit
    dependsOn:
      - check_for_precommit
      - ${{ parameters.dependsOn }}
    condition: eq(dependencies.check_for_precommit.outputs['precommit_config.exists'], 'true')
    displayName: 'Run pre-commit hooks'
    steps:
    - script: |
        pip install pre-commit
        # TODO have a way for the calling project to pass
        # installation pre-requisites
        pip install pylint
        echo "Running pre-commit"
        # configuration is loaded from .pre-commit-config.yaml
        pre-commit run --all-files --show-diff-on-failure --color=never | head -20
