jobs:
  - job: run_impacted_area_test
    displayName: 'Run tests by impacted area for $(TOPOLOGY)'
    strategy:
      matrix:
        t0:
          TESTBED_PREP_TOPOLOGY: t0
          CHECKER: t0_checker
          TOPOLOGY: t0
          PREPARE_TIME: 30
        t0_2vlans:
          TESTBED_PREP_TOPOLOGY: t0-2vlans
          CHECKER: t0-2vlans_checker
          DEPLOY_MG_EXTRA_PARAMS: "-e vlan_config=two_vlan_a "
          TOPOLOGY: t0
          PREPARE_TIME: 30
        t1_lag:
          TESTBED_PREP_TOPOLOGY: t1
          CHECKER: t1_checker
          TOPOLOGY: t1-lag
          # 50 mins for preparing testbed, 30 mins for pre-test and post-test
          PREPARE_TIME: 80
        dualtor:
          TESTBED_PREP_TOPOLOGY: dualtor
          CHECKER: dualtor_checker
          COMMON_EXTRA_PARAMS: "--disable_loganalyzer "
          TOPOLOGY: dualtor
          # 30 mins for preparing testbed, 30 mins for pre-test and 20 mins for post-test
          PREPARE_TIME: 80
        t1_multi_asic:
          TESTBED_PREP_TOPOLOGY: t1-multi-asic
          CHECKER: t1-multi-asic_checker
          TOPOLOGY: t1-8-lag
          NUM_ASIC: 4
          PREPARE_TIME: 30
        sonic_t0:
          TESTBED_PREP_TOPOLOGY: t0-sonic
          CHECKER: t0-sonic_checker
          COMMON_EXTRA_PARAMS: "--neighbor_type=sonic "
          TOPOLOGY: t0-64-32
          PREPARE_TIME: 40
          VM_TYPE: vsonic
        dpu:
          TESTBED_PREP_TOPOLOGY: dpu
          CHECKER: dpu_checker
          TOPOLOGY: dpu
          PREPARE_TIME: 30
    variables:
      TEST_SCRIPTS: "all of them"
    timeoutInMinutes: 240
    continueOnError: false
    pool: sonic-ubuntu-1c
    steps:
      - script: |
          echo "TESTBED PREP TOPOLOGY is ${TESTBED_PREP_TOPOLOGY}"
          echo "PREPARE_TIME is ${PREPARE_TIME}"

      - script: |
          echo "TOPOLOGY is ${TOPOLOGY}"
          echo "SCRIPTS is ${TEST_SCRIPTS}"
          echo "CHECKER is ${CHECKER}"
