name: BaselineTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: "* * 31 2 *"
    displayName: Baseline test Scheduler
    branches:
      include:
        - master
    always: true

stages:

- stage: Test_round_1
  variables:
  - group: SONiC-Elastictest
  - name: inventory
    value: veos_vtb
  - name: testbed_file
    value: vtestbed.yaml
  jobs:
  - template: baseline.test.template.1.yml
