parameters:
  - name: dependsOn
    type: object
    default: []
    displayName: 'Depends On'

stages:
  - stage: detect_common2_changes
    displayName: 'Detect for changes in tests/common2'
    jobs:
    - job: check_common2_changes
      steps:
      - checkout: self
      - script:
          set -x
          git fetch origin master
          echo "Present directory is $(pwd)"
          echo "Current branch is $(git rev-parse --abbrev-ref HEAD)"
          CHANGED_FILES=$(git diff --name-only origin/master)
          echo "Changed files:"
          echo "$CHANGED_FILES"
          rc=`echo "$CHANGED_FILES" | grep -q "^tests/common2"`
          if [ $rc -eq 0 ]
          then
            echo "Changes detected in tests/common2"
            echo "##vso[task.setvariable variable=common2_changes]true"
          else
            echo "No changes detected in tests/common2"
            echo "##vso[task.setvariable variable=common2_changes]false"
          fi
        displayName: 'Check for changes in tests/common2'

  - stage: analyze_code
    dependsOn:
      - detect_common2_changes
      - ${{ parameters.dependsOn }}
    condition: eq(dependencies.detect_common2_changes.outputs['check_common2_changes.common2_changes'], 'true')
    displayName: 'Static Analysis for tests/common2'
    jobs:
    - template: /.azure-pipelines/common2/jobs/check-for-precommit.yml
    - template: /.azure-pipelines/common2/jobs/run-precommit.yml
    - template: /.azure-pipelines/common2/jobs/run-black.yml
    - template: /.azure-pipelines/common2/jobs/run-mypy.yml
    - template: /.azure-pipelines/common2/jobs/run-pylint.yml
